
import './globals.css'
import { Sora } from 'next/font/google'
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

const inter = Sora({ 
  subsets: ['latin'],
  weight: ["400","500","600", "700", "800"]
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
